#!/usr/bin/env bash
# cai-common.sh — shared helpers for Claude Code + CAI Inference in Workbench runtime.
# Sourced by cai-runtime-startup.sh. Do not execute directly.
#
# Workbench env vars (set in Project → Settings → Environment Variables):
#   CAII_OPENAI_BASE_URL — OpenAI-compatible base URL (vLLM: .../openai/v1 ; NIM: .../v1)
#   CAII_API_TOKEN       — Bearer token (CDP JWT); if unset, read access_token from /tmp/jwt
#   CAII_MODEL           — model id for chat/completions (e.g. kevinbtalbert/Devstral-Small-2507)
#   CAII_LITELLM_PORT    — local LiteLLM proxy port (default: 4000)

: "${CAI_HOME:?CAI_HOME must be set before sourcing cai-common.sh}"

LITELLM_CONFIG="${CAI_LITELLM_CONFIG:-${CAI_HOME}/litellm-config.yaml}"
LITELLM_PID_FILE="${CAI_LITELLM_PID_FILE:-${CAI_HOME}/litellm.pid}"
LITELLM_LOG="${CAI_LITELLM_LOG:-${CAI_HOME}/litellm.log}"
LITELLM_PORT="${CAII_LITELLM_PORT:-${CAI_LITELLM_PORT:-4000}}"
LITELLM_MASTER_KEY="${CAI_LITELLM_MASTER_KEY:-sk-cai-local-proxy}"
PROXY_URL="http://127.0.0.1:${LITELLM_PORT}"

CLAUDE_OPUS_ALIAS="${CAI_CLAUDE_OPUS_ALIAS:-claude-opus-4-6}"
CLAUDE_SONNET_ALIAS="${CAI_CLAUDE_SONNET_ALIAS:-claude-sonnet-4-6}"
CLAUDE_HAIKU_ALIAS="${CAI_CLAUDE_HAIKU_ALIAS:-claude-haiku-4-5-20251001}"

cai_log() { printf '%s\n' "$*" >&2; }
cai_die() { cai_log "ERROR: $*"; return 1; }

cai_have_cmd() { command -v "$1" >/dev/null 2>&1; }

cai_ensure_caii_token() {
    if [[ -n "${CAII_API_TOKEN:-}" ]]; then
        return 0
    fi
    if [[ ! -r /tmp/jwt ]]; then
        return 1
    fi
    local token=""
    token="$(python3 -c 'import json; print(json.load(open("/tmp/jwt"))["access_token"])' 2>/dev/null)" || return 1
    if [[ -n "$token" ]]; then
        export CAII_API_TOKEN="$token"
    fi
}

cai_caii_env_ready() {
    cai_ensure_caii_token
    [[ -n "${CAII_OPENAI_BASE_URL:-}" && -n "${CAII_API_TOKEN:-}" && -n "${CAII_MODEL:-}" ]]
}

cai_normalize_url() {
    local url="${1:-}" token="${2:-}"
    url="${url%/}"

    case "$url" in
        */openai/v1|*/v1)
            printf '%s' "$url"
            return 0
            ;;
    esac

    local try_openai="${url}/openai/v1"
    local try_v1="${url}/v1"
    if curl -sf -o /dev/null --connect-timeout 8 --max-time 15 \
        -H "Authorization: Bearer ${token}" "${try_openai}/models" 2>/dev/null; then
        printf '%s' "$try_openai"
        return 0
    fi
    if curl -sf -o /dev/null --connect-timeout 8 --max-time 15 \
        -H "Authorization: Bearer ${token}" "${try_v1}/models" 2>/dev/null; then
        printf '%s' "$try_v1"
        return 0
    fi

    cai_die "Could not reach ${url}. Expected .../v1 (NIM) or .../openai/v1 (vLLM)." || return 1
}

cai_detect_endpoint_kind() {
    case "$1" in
        */openai/v1) printf 'vllm' ;;
        */v1) printf 'nim' ;;
        *) printf 'unknown' ;;
    esac
}

cai_litellm_bin() {
    local bin="${CAI_VENV_BIN:-/opt/cai-claude/venv/bin}/litellm"
    [ -x "$bin" ] || { cai_die "LiteLLM not installed at ${bin}"; return 1; }
    printf '%s' "$bin"
}

cai_write_litellm_config() {
    local base_url model openai_model
    base_url="${CAII_OPENAI_BASE_URL%/}"
    model="${CAII_MODEL}"
    openai_model="openai/${model}"

    mkdir -p "$(dirname "$LITELLM_CONFIG")"
    cat >"$LITELLM_CONFIG" <<YAML
# Generated by Claude Code + CAI Inference runtime
model_list:
  - model_name: ${CLAUDE_OPUS_ALIAS}
    litellm_params:
      model: ${openai_model}
      api_base: ${base_url}
      api_key: os.environ/CAII_API_TOKEN
  - model_name: ${CLAUDE_SONNET_ALIAS}
    litellm_params:
      model: ${openai_model}
      api_base: ${base_url}
      api_key: os.environ/CAII_API_TOKEN
  - model_name: ${CLAUDE_HAIKU_ALIAS}
    litellm_params:
      model: ${openai_model}
      api_base: ${base_url}
      api_key: os.environ/CAII_API_TOKEN

litellm_settings:
  master_key: ${LITELLM_MASTER_KEY}
  drop_params: true
YAML
}

cai_proxy_health_ok() {
    curl -sf --connect-timeout 2 --max-time 5 \
        -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
        "${PROXY_URL}/health/liveliness" >/dev/null 2>&1 \
        || curl -sf --connect-timeout 2 --max-time 5 "${PROXY_URL}/health" >/dev/null 2>&1
}

cai_stop_proxy() {
    if [ -f "$LITELLM_PID_FILE" ]; then
        local pid
        pid="$(cat "$LITELLM_PID_FILE" 2>/dev/null || true)"
        if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            wait "$pid" 2>/dev/null || true
        fi
        rm -f "$LITELLM_PID_FILE"
    fi
}

cai_start_litellm_proxy() {
    local litellm_bin new_hash="" old_hash=""
    cai_caii_env_ready || { cai_die "CAII env not ready — set CAII_OPENAI_BASE_URL, CAII_MODEL, and token."; return 1; }

    litellm_bin="$(cai_litellm_bin)" || return 1
    cai_write_litellm_config

    if cai_have_cmd shasum; then
        new_hash="$(shasum -a 256 "$LITELLM_CONFIG" | awk '{print $1}')"
        old_hash="$(cat "${LITELLM_CONFIG}.hash" 2>/dev/null || true)"
    fi

    if cai_proxy_health_ok && [ -n "$new_hash" ] && [ "$new_hash" = "$old_hash" ]; then
        return 0
    fi

    cai_stop_proxy
    export CAII_API_TOKEN
    export LITELLM_USE_CHAT_COMPLETIONS_URL_FOR_ANTHROPIC_MESSAGES="${LITELLM_USE_CHAT_COMPLETIONS_URL_FOR_ANTHROPIC_MESSAGES:-true}"
    : >"$LITELLM_LOG"

    "$litellm_bin" --config "$LITELLM_CONFIG" --host 127.0.0.1 --port "$LITELLM_PORT" \
        >>"$LITELLM_LOG" 2>&1 &
    local pid=$!
    echo "$pid" >"$LITELLM_PID_FILE"

    local i
    for i in $(seq 1 30); do
        if cai_proxy_health_ok; then
            [ -n "$new_hash" ] && printf '%s' "$new_hash" >"${LITELLM_CONFIG}.hash"
            return 0
        fi
        if ! kill -0 "$pid" 2>/dev/null; then
            cai_log "LiteLLM failed to start. Last log lines:"
            tail -20 "$LITELLM_LOG" >&2 || true
            cai_die "LiteLLM proxy exited unexpectedly." || return 1
        fi
        sleep 0.5
    done
    cai_die "LiteLLM proxy did not become healthy within 15s. See ${LITELLM_LOG}" || return 1
}

cai_write_claude_settings() {
    mkdir -p "$HOME/.claude"
    umask 077

    cat >"$HOME/.claude.json" <<EOF
{
  "hasCompletedOnboarding": true,
  "primaryApiKey": "${LITELLM_MASTER_KEY}"
}
EOF

    cat >"$HOME/.claude/settings.json" <<EOF
{
  "promptSuggestionEnabled": false,
  "env": {
    "ANTHROPIC_BASE_URL": "${PROXY_URL}",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "${CLAUDE_OPUS_ALIAS}",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "${CLAUDE_SONNET_ALIAS}",
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "${CLAUDE_HAIKU_ALIAS}",
    "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY": "1",
    "CLAUDE_CODE_ATTRIBUTION_HEADER": "0",
    "CLAUDE_CODE_ENABLE_TELEMETRY": "0",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
    "LITELLM_USE_CHAT_COMPLETIONS_URL_FOR_ANTHROPIC_MESSAGES": "${LITELLM_USE_CHAT_COMPLETIONS_URL_FOR_ANTHROPIC_MESSAGES:-true}"
  },
  "attribution": { "commit": "", "pr": "" }
}
EOF
}

cai_export_claude_env() {
    export ANTHROPIC_BASE_URL="$PROXY_URL"
    export ANTHROPIC_API_KEY="$LITELLM_MASTER_KEY"
    unset ANTHROPIC_AUTH_TOKEN
    export ANTHROPIC_DEFAULT_OPUS_MODEL="$CLAUDE_OPUS_ALIAS"
    export ANTHROPIC_DEFAULT_SONNET_MODEL="$CLAUDE_SONNET_ALIAS"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL="$CLAUDE_HAIKU_ALIAS"
    export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY="${CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY:-1}"
    export LITELLM_USE_CHAT_COMPLETIONS_URL_FOR_ANTHROPIC_MESSAGES="${LITELLM_USE_CHAT_COMPLETIONS_URL_FOR_ANTHROPIC_MESSAGES:-true}"
}

cai_sync_config() {
    local verbose="${1:-0}" base_url endpoint_kind

    if ! cai_caii_env_ready; then
        cai_log "claude-sync-config: set CAII_OPENAI_BASE_URL and CAII_MODEL; set CAII_API_TOKEN or provide /tmp/jwt."
        return 1
    fi

    base_url="$(cai_normalize_url "$CAII_OPENAI_BASE_URL" "$CAII_API_TOKEN")" || return 1
    export CAII_OPENAI_BASE_URL="$base_url"
    endpoint_kind="$(cai_detect_endpoint_kind "$base_url")"

    cai_write_claude_settings
    cai_start_litellm_proxy || return 1
    cai_export_claude_env

    if [[ "$verbose" == "1" ]]; then
        cai_log "LiteLLM proxy: ${PROXY_URL} → ${CAII_OPENAI_BASE_URL} (${endpoint_kind})"
        cai_log "Model: ${CAII_MODEL}"
        cai_log "Token: CAII_API_TOKEN env (not written to disk)"
        cai_log "Ready: claude"
    fi
}

cai_launch_claude() {
    cai_have_cmd claude || { cai_die "Claude Code CLI not installed."; return 127; }
    cai_sync_config 0 || return 1

    if [ $# -gt 0 ]; then
        command claude "$@"
    else
        command claude
    fi
}
